### ISSUE TITLE
Can't save the rating filter 

### ISSUE THREAD

**Issue by SinghVerm** [chithakumar13/Fifa21-RatingFilter#2]
it stucks on loading when i tried to put any rating and save in the settings. i have tried all three version and my chrome is up to date

**Comment by ckalgos** [comment]
Can you press F12 in the browser , go to console tab and see if there is any error ?,  Send the errors here if you find any

**Comment by SinghVerm** [comment]
i hope this 
helps

**Comment by ckalgos** [comment]
@SinghVerm , there is some issue with different webapp locale, for now use the default locale using this https://www.ea.com/fifa/ultimate-team/web-app/ , will fix the issue shortly
