### ISSUE TITLE
Does not save

### ISSUE THREAD

**Issue by RickSiar** [chithakumar13/Fifa21-RatingFilter#7]
There is a problem when saving the rating

**Comment by RickSiar** [comment]
![image](https://user-images.githubusercontent.com/77945328/105663117-53a9b380-5ec9-11eb-87e3-9339964bb6de.png)

**Comment by RickSiar** [comment]
Keeps getting this 403 error eeven though  I tried changing the database URL but nothing is working

**Comment by ckalgos** [comment]
Use this link to access web app https://www.ea.com/fifa/ultimate-team/web-app/

Also try reading Readme, sometimes it might have answers to your issue.
