### ISSUE TITLE
Kindly read this carefully- Saving problem

### ISSUE THREAD

**Issue by RickSiar** [chithakumar13/Fifa21-RatingFilter#8]
Hello sir, I tried the rating tool on the fifa 21 webapp from the link provided, read the "read.me", watched the demo. Even tried it on multiple accounts, but it wont work for some reason. Everytime I insert a rate an hit save, I enter this loop of saving that never ends and in the console log i get 403 error. I know how to use tampermonkey and the webapp. Please advice me on what would make this work. Thanks in advance

**Comment by ckalgos** [comment]
The console log error image you shared has en-gb, meaning you are accessing web app using https://www.ea.com/en-gb/fifa/ultimate-team/web-app/ and not https://www.ea.com/fifa/ultimate-team/web-app/
